### ISSUE TITLE
missing j2objc

### ISSUE THREAD

**Issue by saruye** [TriangleLeft/Flashcards#17]
hi, 

I found your repository through your post on reddit and found it as a valuable resource for a project setup with j2objc and android together. Now I saw that you removed j2objc. Are there any reasons why you are not supporting this anymore? 

Regards, 
arne

**Comment by alekseikurnosenko** [comment]
It was too bothersome to continue supporting both versions, especially since I don't plan to release it on iOS. 
Tag 1.1.1 is the last supported one.

**Comment by alekseikurnosenko** [comment]
Master branch reverted to tag 1.1.1
