### ISSUE TITLE
Task 'j2objcBuild' not found in project ':core'.

### ISSUE THREAD

**Issue by pernilla** [TriangleLeft/Flashcards#18]
According to your instructions you say run build_framework.sh, but it points to a target in core project which does not exist. 

So how do I run this for iOS? 

Also, you point to a branch that doesn't exist anymore in Podfile: 

pod 'HanekeSwift', git: 'https://github.com/Haneke/HanekeSwift.git', branch: 'feature/swift-2.3'

should be replaced by

pod 'HanekeSwift', git: 'https://github.com/Haneke/HanekeSwift.git', branch: 'feature/swift-3'

**Comment by alekseikurnosenko** [comment]
Sorry, I should've updated readme, latest master doesn't support j2objc anymore.
Tag 1.1.1 is the last supported one.

**Comment by alekseikurnosenko** [comment]
Master branch reverted to tag 1.1.1
