### ISSUE TITLE
Publish APK on Github?

### ISSUE THREAD

**Issue by IzzySoft** [TriangleLeft/Flashcards#19]
Would you consider publishing the `.apk` file here at Github (e.g. with the `releases/`), so folks without Playstore can access it?

**Comment by alekseikurnosenko** [comment]
Done: https://github.com/TriangleLeft/Flashcards/releases/download/1.3/flashcards-release.apk

**Comment by IzzySoft** [comment]
Thanks a lot! I've just added it to my F-Droid compatible repo (see [here](https://apt.izzysoft.de/fdroid/index/apk/com.triangleleft.flashcards)). Whenever you publish an update and add the `.apk` to the release, it should be updated there within 24h usually. So be welcome to refer "Playstore-abstinents" to it :innocent:
