### ISSUE TITLE
Flashcards status and future

### ISSUE THREAD

**Issue by licaon-kter** [TriangleLeft/Flashcards#23]
...given current dev pacing and given that DuoLingo Tinycards is out for Android?

**Comment by alekseikurnosenko** [comment]
I probably won't be updating this app anymore. I stopped using the flashcards are they are pretty useless - in German, they don't include articles, and without a proper context, translation usually makes no sense.
And it seems I am not the only one, as Duolingo also removed it from their web version.

**Comment by licaon-kter** [comment]
Can you at least update the README to reflect the development status?
